/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './hooks/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Surfaces ──
        bg: 'rgb(var(--color-bg) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--color-surface-2) / <alpha-value>)',

        // ── Text ──
        text: 'rgb(var(--color-text) / <alpha-value>)',
        'text-muted': 'rgb(var(--color-text-muted) / <alpha-value>)',
        'text-faint': 'rgb(var(--color-text-faint) / <alpha-value>)',

        // ── Brand accent ──
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-dim': 'rgba(var(--color-accent) / 0.12)',

        // ── Semantic states ──
        ok: 'rgb(var(--color-ok) / <alpha-value>)',
        'ok-dim': 'rgba(var(--color-ok) / 0.10)',
        warn: 'rgb(var(--color-warn) / <alpha-value>)',
        'warn-dim': 'rgba(var(--color-warn) / 0.10)',
        destructive: 'rgb(var(--color-destructive) / <alpha-value>)',
        'destructive-dim': 'rgba(var(--color-destructive) / 0.10)',

        // ── Borders ──
        border: 'rgba(var(--color-text) / 0.10)',
        'border-strong': 'rgba(var(--color-text) / 0.18)',

        // ── shadcn-style aliases (mirror web index.css) ──
        background: 'rgb(var(--color-bg) / <alpha-value>)',
        foreground: 'rgb(var(--color-text) / <alpha-value>)',
        card: 'rgb(var(--color-surface) / <alpha-value>)',
        'card-foreground': 'rgb(var(--color-text) / <alpha-value>)',
        primary: 'rgb(var(--color-accent) / <alpha-value>)',
        'primary-foreground': '#ffffff',
        secondary: 'rgb(var(--color-surface-2) / <alpha-value>)',
        'secondary-foreground': 'rgb(var(--color-text-muted) / <alpha-value>)',
        muted: 'rgb(var(--color-surface-2) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--color-text-faint) / <alpha-value>)',
        ring: 'rgb(var(--color-accent) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Poppins_400Regular'],
        medium: ['Poppins_500Medium'],
        semibold: ['Poppins_600SemiBold'],
        bold: ['Poppins_700Bold'],
        display: ['Poppins_700Bold'],
      },
      fontSize: {
        // Mirrors the web's 15px html base + Tailwind's default scale
        '2xs': '10px',
        xs: '11px',
        sm: '12px',
        base: '14px',
        md: '15px',
        lg: '16px',
        xl: '18px',
        '2xl': '20px',
        '3xl': '24px',
        '4xl': '28px',
        '5xl': '32px',
        '6xl': '40px',
      },
      borderRadius: {
        none: '0px',
        sm: '8px',
        DEFAULT: '10px',
        md: '10px',
        lg: '14px',
        xl: '20px',
        '2xl': '24px',
        pill: '99px',
        full: '9999px',
      },
      spacing: {
        // 4px-step scale matching Tailwind defaults
        0: '0px',
        px: '1px',
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        3.5: '14px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
        14: '56px',
        16: '64px',
        20: '80px',
        24: '96px',
        28: '112px',
        32: '128px',
        36: '144px',
        40: '160px',
        48: '192px',
        56: '224px',
        64: '256px',
        72: '288px',
        80: '320px',
        96: '384px',
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0em',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      lineHeight: {
        tight: '1.2',
        snug: '1.35',
        normal: '1.5',
        relaxed: '1.6',
        loose: '1.8',
      },
    },
  },
  plugins: [],
};
